# Base image
FROM python:3.9

# Set working directory
WORKDIR /garden

# Copy requirements.txt file to container
COPY requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt

# Copy garden files to container
COPY . .

# Expose port 8080
EXPOSE 8080

# Run the garden when the container starts
CMD ["python", "garden.py"]
